apiVersion: v1
kind: Service
metadata:
  name: wasm-doom
spec:
  selector:
    app: wasm-doom
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}